nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://scale-307185671274.d.codeartifact.us-west-2.amazonaws.com/npm/scale-npm/"
    npmRegistryServer: "https://scale-307185671274.d.codeartifact.us-west-2.amazonaws.com/npm/scale-npm/"
  scale:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://scale-307185671274.d.codeartifact.us-west-2.amazonaws.com/npm/scale-npm/"
    npmRegistryServer: "https://scale-307185671274.d.codeartifact.us-west-2.amazonaws.com/npm/scale-npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-aws-codeartifact.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-aws-codeartifact/v0.10.1/bundles/@yarnpkg/plugin-aws-codeartifact.js"

yarnPath: .yarn/releases/yarn-4.0.2.cjs