npmScopes:
  fortawesome:
    npmRegistryServerConfig:
      awsProfile: production-developer
      preferAwsEnvironmentCredentials: true
    npmPublishRegistryConfig:
      awsProfile: production-developer
      preferAwsEnvironmentCredentials: true
  scale:
    npmRegistryServerConfig:
      awsProfile: production-developer
      preferAwsEnvironmentCredentials: true
    npmPublishRegistryConfig:
      awsProfile: production-developer
      preferAwsEnvironmentCredentials: true
